server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      console.settings.trace: false
      spring.h2.console.web-allow-others: false
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-slq: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
